export {
  CHAT_MESSAGES_PAGE_DEFAULT,
  ORDER_CHAT_ATTACHMENT_REFS_PAYLOAD_MAX_CHARS,
  ORDER_CHAT_ATTACHMENTS_MAX,
  ORDER_CHAT_DELETE_WITHIN_MS,
  ORDER_CHAT_POST_BODY_MAX_CHARS,
  ORDER_CHAT_SOCKET_NAMESPACE,
  ORDER_CHAT_SOCKET_UPDATED_EVENT,
  ORDER_CHAT_UPLOAD_MAX_FILE_BYTES,
  ORDER_CHAT_WS_REFRESH_BUFFER_MS,
  ORDER_CHAT_WS_REFRESH_FALLBACK_MS,
  isOrderChatMessageWithinDeleteWindow,
  type OrderChatVariant,
} from '@miraflores/order-chat-core';

/** Только витрина (placeholder аватара staff в ЛК). */
export const ORDER_CHAT_STAFF_AVATAR_PLACEHOLDER = '/images/favicon-mira.svg';
